// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package java

import (
	"bufio"
	"errors"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"syscall"

	"github.com/googleapis/librarian/internal/config"
)

var itTestRegexp = regexp.MustCompile(`src/test/java/com/google/cloud/.*/v.*/it/IT.*Test\.java$`)
var versionRegexp = regexp.MustCompile(`src/main/java/com/google/cloud/.*/v.*/stub/Version\.java$`)

const (
	autoGeneratedMarker     = "// AUTO-GENERATED DOCUMENTATION AND CLASS."
	autoGeneratedAnnotation = "@Generated(\"by gapic-generator-java\")"
)

var generatedNonJavaFiles = []string{
	"gapic_metadata.json",
	"reflect-config.json",
}

// generateIfMissingFiles are files that are manually maintained after creation. Bypass in clean.
var generateIfMissingFiles = []string{
	"clirr-ignored-differences.xml",
	"pom.xml",
}

// Clean removes files in the library's output directory that are not in the keep list.
// It targets patterns like proto-*, grpc-*, and the main GAPIC module.
func Clean(library *config.Library) error {
	patterns := cleanPatterns(library)
	keepSet := make(map[string]bool)
	for _, k := range library.Keep {
		keepSet[filepath.ToSlash(k)] = true
	}
	for pattern, useMarker := range patterns {
		matches, err := filepath.Glob(filepath.Join(library.Output, pattern))
		if err != nil {
			return err
		}
		for _, match := range matches {
			if err := cleanPath(match, library.Output, keepSet, useMarker); err != nil {
				return err
			}
		}
	}
	return nil
}

func cleanPatterns(library *config.Library) map[string]bool {
	libraryCoordinates := DeriveLibraryCoordinates(library)
	patterns := map[string]bool{
		filepath.Join("samples", "snippets", "generated"): false,
		".repo-metadata.json":                             false,
	}
	for _, api := range library.APIs {
		javaAPI := ResolveJavaAPI(library, api)
		version := filepath.Base(api.Path)
		apiCoordinates := DeriveAPICoordinates(libraryCoordinates, version, javaAPI)
		if apiCoordinates.Proto.ArtifactID != "" {
			patterns[filepath.Join(apiCoordinates.Proto.ArtifactID, "src")] = false
		}
		if apiCoordinates.GRPC.ArtifactID != "" {
			patterns[filepath.Join(apiCoordinates.GRPC.ArtifactID, "src")] = false
		}
		if apiCoordinates.GAPIC.ArtifactID != "" {
			patterns[filepath.Join(apiCoordinates.GAPIC.ArtifactID, "src")] = true
		}
	}
	return patterns
}

func cleanPath(targetPath, root string, keepSet map[string]bool, useMarker bool) error {
	var dirs []string
	err := filepath.WalkDir(targetPath, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			if keepSet[filepath.ToSlash(rel)] {
				return filepath.SkipDir
			}
			dirs = append(dirs, path)
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		relSlash := filepath.ToSlash(rel)
		if shouldPreserve(relSlash, keepSet) {
			return nil
		}
		if slices.Contains(generateIfMissingFiles, d.Name()) {
			return nil
		}
		if useMarker {
			shouldClean, err := shouldCleanMarkerPath(path, d)
			if err != nil {
				return err
			}
			if !shouldClean {
				return nil
			}
		}
		return os.Remove(path)
	})
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	// Remove empty directories in reverse order (bottom-up).
	for i := len(dirs) - 1; i >= 0; i-- {
		d := dirs[i]
		rel, err := filepath.Rel(root, d)
		if err != nil {
			return err
		}
		if !keepSet[filepath.ToSlash(rel)] {
			if err := os.Remove(d); err != nil && !errors.Is(err, fs.ErrNotExist) && !isDirNotEmpty(err) {
				return err
			}
		}
	}
	return nil
}

// isDirNotEmpty returns true if err indicates the directory is not empty.
func isDirNotEmpty(err error) bool {
	return errors.Is(err, syscall.ENOTEMPTY) || errors.Is(err, syscall.EEXIST)
}

// shouldPreserve returns true if the given slash-separated path should be preserved
// based on the keepSet or standard preservation patterns.
func shouldPreserve(path string, keepSet map[string]bool) bool {
	return keepSet[path] || itTestRegexp.MatchString(path) || versionRegexp.MatchString(path)
}

// shouldCleanMarkerPath returns true if the file at path should be cleaned based on
// its name or whether it contains the auto-generated marker.
func shouldCleanMarkerPath(path string, d os.DirEntry) (bool, error) {
	if slices.Contains(generatedNonJavaFiles, d.Name()) {
		return true, nil
	}
	if filepath.Ext(path) != ".java" {
		return false, nil
	}
	return hasMarker(path)
}

// hasMarker checks if the file at path contains the auto-generated marker.
// It scans the file line by line using [bufio.Reader] and returns true as soon
// as the marker is found, avoiding reading the entire file.
func hasMarker(path string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer func() {
		if cerr := f.Close(); err == nil {
			err = cerr
		}
	}()

	reader := bufio.NewReader(f)
	for {
		line, rerr := reader.ReadString('\n')
		if strings.Contains(line, autoGeneratedMarker) || strings.Contains(line, autoGeneratedAnnotation) {
			return true, nil
		}
		if rerr != nil {
			if errors.Is(rerr, io.EOF) {
				break
			}
			return false, rerr
		}
	}
	return false, nil
}
